# Generated by Django 5.2.11 on 2026-05-05 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0002_seed_rural_clinics'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='is_govt',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='clinic',
            name='services',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='clinic',
            name='state',
            field=models.CharField(default='Bihar', max_length=100),
        ),
        migrations.AddField(
            model_name='clinic',
            name='type',
            field=models.CharField(choices=[('PHC', 'Primary Health Centre'), ('CHC', 'Community Health Centre'), ('District Hospital', 'District Hospital'), ('Sub-District Hospital', 'Sub-District Hospital'), ('Private Clinic', 'Private Clinic')], default='PHC', max_length=30),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='phone',
            field=models.CharField(default='104', max_length=20),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='pincode',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='verified',
            field=models.BooleanField(default=True),
        ),
    ]
